build:
    environment:
        php: 7.3.0

    dependencies:
        before:
            # Download latest Composer installer
            - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            - php composer-setup.php --install-dir=$HOME/bin --filename=composer
            - php -r "unlink('composer-setup.php');"
            - $HOME/bin/composer --version
        override:
            - $HOME/bin/composer install --no-interaction --prefer-dist --optimize-autoloader

    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run

filter:
    excluded_paths: [tests/*]

checks:
    php:
        remove_extra_empty_lines: true
        remove_php_closing_tag: true
        remove_trailing_whitespace: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: true
            order_alphabetically: true
        fix_php_opening_tag: true
        fix_linefeed: true
        fix_line_ending: true
        fix_identation_4spaces: true
        fix_doc_comments: true

tools:
    external_code_coverage: true
