<?php

use Illuminate\Support\Facades\Blade;
use Illuminate\Support\MessageBag;
use Illuminate\Support\ViewErrorBag;

/**
 * Set of helpers shared by the blade components test cases. It provides a way
 * to render the components and to assert the AdminLTE v4 (Bootstrap 5.3)
 * contract over the resulting markup.
 */
trait ComponentTestHelpers
{
    /**
     * The set of legacy tokens that must not appear on the markup generated by
     * the components anymore. They belong to AdminLTE v3, to Bootstrap 4 or to
     * Font Awesome, all of them dropped by the AdminLTE v4 migration.
     *
     * @var array
     */
    protected $legacyMarkupTokens = [
        'fa fa-', 'fas ', 'far ', 'fab ',
        'data-widget=', 'data-card-widget',
        'data-toggle=', 'data-dismiss=', 'data-target=',
        'input-group-prepend', 'input-group-append',
        'form-group', 'custom-select', 'custom-control', 'custom-file',
        'sr-only', 'btn-flat', 'badge-primary',
        'float-left', 'float-right',
    ];

    /**
     * Holds the content pushed into the 'js' and 'css' stacks by the last
     * rendered template.
     *
     * @var string
     */
    protected $pushedAssets = '';

    /**
     * Render a blade template holding one (or more) package components. Note
     * the content pushed into the 'js' and 'css' stacks is captured apart, it
     * is available through the renderPushedAssets() method.
     *
     * @param  string  $template  The blade template to render
     * @return string
     */
    protected function renderComponent($template)
    {
        // The '$errors' view variable is normally shared by the Laravel
        // session middleware, which does not take part on a direct render.

        if (! view()->shared('errors')) {
            view()->share('errors', new ViewErrorBag());
        }

        // Note the stacks are flushed at the end of every render, so they
        // need to be yielded within the same render call.

        $separator = '<!--ADMINLTE_PUSHED_ASSETS-->';

        // A named slot leaves its output buffer open on this direct render
        // path, so the level is restored once the render is done.

        $obLevel = ob_get_level();

        $output = Blade::render(
            "{$template}\n{$separator}\n@stack('js')\n@stack('css')"
        );

        while (ob_get_level() > $obLevel) {
            ob_end_clean();
        }

        [$markup, $this->pushedAssets] = explode($separator, $output, 2);

        return $markup;
    }

    /**
     * Get the content pushed into the 'js' and 'css' stacks by the last
     * rendered template.
     *
     * @return string
     */
    protected function renderPushedAssets()
    {
        return $this->pushedAssets;
    }

    /**
     * Setup a validation error for each one of the provided keys. The errors
     * are made available both on the session and on the shared view bag.
     *
     * @param  array|string  $keys  The keys holding a validation error
     * @return void
     */
    protected function setValidationErrorsFor($keys)
    {
        $msgBag = new MessageBag();

        foreach ((array) $keys as $key) {
            $msgBag->add($key, "The {$key} value is invalid.");
        }

        $viewBag = (new ViewErrorBag())->put('default', $msgBag);

        session()->put('errors', $viewBag);
        view()->share('errors', $viewBag);
    }

    /**
     * Assert the rendered markup does not contain any of the legacy tokens
     * that were dropped by the AdminLTE v4 (Bootstrap 5.3) migration.
     *
     * @param  string  $html  The rendered markup
     * @return void
     */
    protected function assertV4Markup($html)
    {
        foreach ($this->legacyMarkupTokens as $token) {
            $this->assertStringNotContainsString(
                $token,
                $html,
                "The rendered markup still contains the legacy '{$token}' token."
            );
        }
    }

    /**
     * Assert the rendered output makes no use of jQuery. AdminLTE v4 dropped
     * the jQuery dependency, so only the components wrapping a plugin that
     * still requires it are allowed to reference it (and only behind a
     * feature guard).
     *
     * @param  string  $output  The rendered output
     * @return void
     */
    protected function assertFreeOfJquery($output)
    {
        $this->assertStringNotContainsString('jQuery', $output);
        $this->assertStringNotContainsString('$(', $output);
    }

    /**
     * Assert the provided javascript only touches jQuery (or a jQuery plugin)
     * after checking that it is actually available, so the script is harmless
     * on an application that does not load the plugin.
     *
     * @param  string  $js  The rendered javascript
     * @param  string  $guard  The feature guard expected before the usage
     * @param  string  $usage  The first usage of the plugin
     * @return void
     */
    protected function assertGuardedPluginUsage($js, $guard, $usage)
    {
        $this->assertStringContainsString($guard, $js);
        $this->assertStringContainsString($usage, $js);

        // The guard must come before any usage of the plugin, otherwise the
        // script would throw when the plugin is not loaded.

        $this->assertLessThan(strpos($js, $usage), strpos($js, $guard));
    }
}
