<?php

require_once __DIR__.'/ComponentTestHelpers.php';

use JeroenNoten\LaravelAdminLte\View\Components;

class ThemeColorsTest extends TestCase
{
    use ComponentTestHelpers;

    /**
     * The complete map of AdminLTE v3 color names that were renamed on the
     * AdminLTE v4 extended palette.
     *
     * @var array
     */
    protected $v3ColorAliases = [
        'lightblue' => 'sky',
        'maroon' => 'pink',
        'purple' => 'violet',
        'lime' => 'olive',
        'blue' => 'primary',
        'red' => 'danger',
        'green' => 'success',
        'yellow' => 'warning',
        'cyan' => 'info',
        'gray' => 'secondary',
        'gray-dark' => 'dark',
    ];

    /**
     * Return the class attribute generated by every component using the
     * 'HandlesThemeColors' trait, together with the pattern used to build the
     * themed CSS class.
     *
     * @param  string  $theme  The theme color to use
     * @return array
     */
    protected function makeThemedClasses($theme)
    {
        $profileCol = new Components\Widget\ProfileColItem(
            null, 'text', null, null, $theme
        );

        $profileRow = new Components\Widget\ProfileRowItem(
            null, 'text', null, null, "pill-{$theme}"
        );

        return [
            'button' => [
                'class' => (new Components\Form\Button(null, 'button', $theme))->theme,
                'pattern' => '%s',
            ],
            'alert' => [
                'class' => (new Components\Widget\Alert($theme))->makeAlertClass(),
                'pattern' => 'alert-%s',
            ],
            'callout' => [
                'class' => (new Components\Widget\Callout($theme))->makeCalloutClass(),
                'pattern' => 'callout-%s',
            ],
            'card' => [
                'class' => (new Components\Widget\Card(null, null, $theme))->makeCardClass(),
                'pattern' => 'card-%s',
            ],
            'card-full' => [
                'class' => (new Components\Widget\Card(null, null, $theme, 'full'))->makeCardClass(),
                'pattern' => 'text-bg-%s',
            ],
            'info-box' => [
                'class' => (new Components\Widget\InfoBox(null, null, null, null, null, null, $theme))->makeBoxClass(),
                'pattern' => 'text-bg-%s',
            ],
            'info-box-icon' => [
                'class' => (new Components\Widget\InfoBox(null, null, null, null, null, null, null, $theme))->makeIconClass(),
                'pattern' => 'text-bg-%s',
            ],
            'profile-col-item' => [
                'class' => $profileCol->makeTextWrapperClass(),
                'pattern' => 'text-bg-%s',
            ],
            'profile-row-item' => [
                'class' => $profileRow->makeTextWrapperClass(),
                'pattern' => 'text-bg-%s',
            ],
            'profile-widget' => [
                'class' => (new Components\Widget\ProfileWidget(null, null, null, $theme))->makeHeaderClass(),
                'pattern' => 'text-bg-%s',
            ],
            'progress' => [
                'class' => (new Components\Widget\Progress(50, $theme))->makeProgressBarClass(),
                'pattern' => 'bg-%s',
            ],
            'small-box' => [
                'class' => (new Components\Widget\SmallBox(null, null, null, $theme))->makeBoxClass(),
                'pattern' => 'text-bg-%s',
            ],
            'modal' => [
                'class' => (new Components\Tool\Modal('id', null, null, null, $theme))->makeModalHeaderClass(),
                'pattern' => 'text-bg-%s',
            ],
        ];
    }

    /*
    |--------------------------------------------------------------------------
    | Theme colors resolution tests.
    |--------------------------------------------------------------------------
    */

    public function testEveryComponentTranslatesTheV3ColorNames()
    {
        // The AdminLTE v3 color names are accepted by every component using
        // the 'HandlesThemeColors' trait and translated to their AdminLTE v4
        // equivalent, so a legacy view keeps working with the v4 palette.

        foreach (['lightblue' => 'sky', 'maroon' => 'pink'] as $v3 => $v4) {
            foreach ($this->makeThemedClasses($v3) as $name => $data) {
                $this->assertStringContainsString(
                    sprintf($data['pattern'], $v4),
                    $data['class'],
                    "The {$name} component does not translate the '{$v3}' color."
                );

                $this->assertStringNotContainsString(
                    sprintf($data['pattern'], $v3),
                    $data['class'],
                    "The {$name} component keeps the legacy '{$v3}' color."
                );
            }
        }
    }

    public function testEveryV3ColorAliasIsTranslated()
    {
        // Test the complete alias map through a single component.

        foreach ($this->v3ColorAliases as $v3 => $v4) {
            $component = new Components\Widget\Callout($v3);

            $this->assertEquals(
                "callout callout-{$v4}",
                $component->makeCalloutClass()
            );
        }
    }

    public function testTheV4ColorNamesAreKeptUntouched()
    {
        // The AdminLTE v4 color names (and the Bootstrap ones) must not be
        // altered by the translation.

        $colors = ['primary', 'danger', 'sky', 'pink', 'teal', 'navy', 'olive'];

        foreach ($colors as $color) {
            foreach ($this->makeThemedClasses($color) as $name => $data) {
                $this->assertStringContainsString(
                    sprintf($data['pattern'], $color),
                    $data['class'],
                    "The {$name} component altered the '{$color}' color."
                );
            }
        }
    }

    public function testTheTranslationIsSkippedWithTheV3AliasesStylesheet()
    {
        // When the v3 alias stylesheet is in use, the AdminLTE v3 color names
        // are real CSS classes, so they must be kept untouched.

        config(['adminlte.assets.extended_colors_v3_aliases' => true]);

        foreach (array_keys($this->v3ColorAliases) as $v3) {
            $component = new Components\Widget\Callout($v3);

            $this->assertEquals(
                "callout callout-{$v3}",
                $component->makeCalloutClass()
            );
        }

        foreach ($this->makeThemedClasses('lightblue') as $name => $data) {
            $this->assertStringContainsString(
                sprintf($data['pattern'], 'lightblue'),
                $data['class'],
                "The {$name} component translated the '{lightblue}' color."
            );
        }
    }

    public function testTheThemeIsResolvedOnTheRenderedMarkup()
    {
        // Test the translation reaches the rendered markup and not only the
        // class builder methods.

        $html = $this->renderComponent(
            '<x-adminlte-card title="t" theme="lightblue"/>'.
            '<x-adminlte-small-box title="t" theme="maroon"/>'.
            '<x-adminlte-button label="b" theme="lightblue"/>'.
            '<x-adminlte-progress :value="50" theme="maroon"/>'
        );

        $this->assertStringContainsString('card-sky', $html);
        $this->assertStringContainsString('text-bg-pink', $html);
        $this->assertStringContainsString('btn-sky', $html);
        $this->assertStringContainsString('bg-pink', $html);

        $this->assertStringNotContainsString('lightblue', $html);
        $this->assertStringNotContainsString('maroon', $html);

        $this->assertV4Markup($html);
    }

    public function testTheThemeIsKeptOnTheRenderedMarkupWithTheV3Aliases()
    {
        config(['adminlte.assets.extended_colors_v3_aliases' => true]);

        $html = $this->renderComponent(
            '<x-adminlte-card title="t" theme="lightblue"/>'.
            '<x-adminlte-small-box title="t" theme="maroon"/>'
        );

        $this->assertStringContainsString('card-lightblue', $html);
        $this->assertStringContainsString('text-bg-maroon', $html);

        $this->assertStringNotContainsString('card-sky', $html);
        $this->assertStringNotContainsString('text-bg-pink', $html);
    }

    public function testTheLegacyButtonDefaultThemeIsMappedToSecondary()
    {
        // Bootstrap 5 does not provide a 'btn-default' class anymore.

        $component = new Components\Form\Button();
        $this->assertEquals('secondary', $component->theme);

        $html = $this->renderComponent('<x-adminlte-button label="b"/>');

        $this->assertStringContainsString('btn btn-secondary', $html);
        $this->assertStringNotContainsString('btn-default', $html);
    }
}
